# data:
train_data: data/train.csv
val_data: data/val.csv
test_data: data/test.csv
batch_size: 32

# model:
input_size: 10
hidden_size: 20
output_size: 1
learning_rate: 0.001

# trainer:
max_epochs: 10
gpus: 1

# optimizer:
optimizer: Adam